export const ScreenName = {
    SplashScreen: "SplashScreen",
    StartMenu: "StartMenu",
    SignUp: "SignUp",
    SignIn: "SignIn",
    ForgetPassword: "ForgetPassword",
    MainTab: "MainTab",
    HomeStack: "HomeStack",
    MyCoursesStack: "MyCoursesStack",
    SearchStack: "SearchStack",
    AccountStack: "AccountStack",
    Home: "Home",
    CourseList: "CourseList",
    CourseDetail: "CourseDetail",
    AuthorList: "AuthorList",
    AuthorDetail: "AuthorDetail",
    MyCourses: "MyCourses",
    Search: "Search",
    SearchResult: "SearchResult",
    SearchResultAll: "SearchResultAll",
    Account: "Account",
    Settings: "Settings",
    CourseDetailInformation: "CourseDetailInformation",
    CourseDetailLesson: "CourseDetailLesson",
    CourseDetailExercise: "CourseDetailExercise",
    CourseDetailComment: "CourseDetailComment"
}
