export const languages = {
    english: {
        sign_in: 'Sign In',
        sign_up: 'Sign Up',
        explore: 'Explore',
        validate_username_error_message: 'Username should have at least 6 characters',
        validate_email_error_message: 'Invalid email address',
        validate_phone_error_message: 'Invalid phone number',
        validate_password_error_message: 'Password should have at least 8 characters',
        validate_confirm_password_error_message: 'Confirm password should be matched',
        username: 'Username',
        email: 'Email',
        phone: 'Phone',
        password: 'Password',
        confirm_password: 'Confirm password',
        forget_password: 'Forget password?',
        or: 'Or',
        sign_in_with_google: 'Sign In With Google',
        forget_password_instruction: 'Enter your registered email to reset password',
        registered_email: 'Registered Email',
        send_email_verification: 'Send Email Verification',
        home: 'Home',
        my_courses: 'My Courses',
        search: 'Search',
        account: 'Account',
        settings: 'Settings',
        change_password: 'Change password',
        sign_out: 'Sign Out',
        recommend_for_you: 'Recommend For You',
        new_release: 'New Release',
        hot_topics: 'Hot Topics',
        top_rating_courses: 'Top Rating',
        top_selling_courses: 'Top Selling',
        top_authors: 'Top Authors',
        delete_all: 'Delete all',
        see_all: 'See all',
        overview: 'Overview',
        lesson: 'Lesson',
        exercise: 'Exercise',
        review: 'Review',
        continue_learning: 'Continue Learning',
        favourite: 'Favourite',
        downloaded: 'Downloaded',
        authors_list: 'Authors List'
    },
    vietnamese: {
        sign_in: 'Đăng Nhập',
        sign_up: 'Đăng Kí',
        explore: 'Khám phá',
        validate_username_error_message: 'Tên đăng nhập cần ít nhất 6 kí tự',
        validate_email_error_message: 'Email không hợp lệ',
        validate_phone_error_message: 'Số điện thoại không hợp lệ',
        validate_password_error_message: 'Mật khẩu cần ít nhật 8 kí tự',
        validate_confirm_password_error_message: 'Mật khẩu xác minh không trùng',
        username: 'Tên đăng nhập',
        email: 'Email',
        phone: 'Số điện thoại',
        password: 'Mật khẩu',
        confirm_password: 'Xác minh mật khẩu',
        forget_password: 'Quên mật khẩu?',
        or: 'Hoặc',
        sign_in_with_google: 'Đăng Nhập Bằng Google',
        forget_password_instruction: 'Nhập Email đăng ký để khôi phục mật khẩu',
        registered_email: 'Email đã đăng ký',
        send_email_verification: 'Gửi Email xác nhận',
        home: 'Trang Chủ',
        my_courses: 'Khoá Học',
        search: 'Tìm Kiếm',
        account: 'Tài Khoản',
        settings: 'Cài Đặt',
        change_password: 'Thay đổi mật khẩu',
        sign_out: 'Đăng Xuất',
        recommend_for_you: 'Gợi Ý Cho Bạn',
        new_release: 'Khoá Học Mới',
        hot_topics: 'Chủ Đề Xu Hướng',
        top_rating_courses: 'Khoá Học Nổi Bật',
        top_selling_courses: 'Khoá Học',
        top_authors: 'Tác Giả Nổi Bật',
        delete_all: 'Xoá hết',
        see_all: 'Xem thêm',
        overview: 'Tổng quan',
        lesson: 'Bài học',
        exercise: 'Bài tập',
        review: 'Bình luận',
        continue_learning: 'Tiếp Tục Học',
        favourite: 'Yêu Thích',
        downloaded: 'Đã Tải',
        authors_list: 'Danh Sách Tác Giả',
    }
}
